### ISSUE TITLE
Allow Self-hosted Instances to be Selected!

### ISSUE THREAD

**Issue by SeizureDB** [nain-F49FF806/sharepaste.oo#2]
Hey, PrivateBin is a platform that you can self host.

**Please**! Allow us to select WHAT PrivateBin instance we want to use! The app is great so far, but that is a HUGE Con to this app! Even in F-Droid it warns about it being an Anti-Feature!

Please consider it, 
Please implement it.

**Comment by nain-F49FF806** [comment]
It's planned, yes. :)  See https://github.com/nain-F49FF806/sharepaste.oo/releases/tag/2024.06.05  
We'll have this in the next release, or the one after.

**Comment by nain-F49FF806** [comment]
Tip/early news: Upcoming release will resolve this. ref commit: [[de225ec](https://github.com/nain-F49FF806/sharepaste.oo/commit/de225ec1574a3ae20bf04856651c5c701c655908)]

**Comment by nain-F49FF806** [comment]
Resolved in recent release [2024.07.02](https://github.com/nain-F49FF806/sharepaste.oo/releases/tag/2024.07.02)

You can find the server configuration in settings page. 
For opening settings, long press on the app icon to reveal the settings shortcut. 

If you use a custom launcher, then look for settings in the shortcuts available for this app.
